name: calendar_planner_view
description: A customizable daily calendar planner view with time-based events and Material 3 design.
version: 0.1.7
homepage: https://github.com/danial2026/calendar_planner_view

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_hooks: ^0.21.2
