import 'package:flutter/widgets.dart';
import 'package:table_calendar/table_calendar.dart';

extension CalendarStyleExtension on CalendarStyle {
  CalendarStyle copyWith({
    int? markersMaxCount,
    bool? canMarkersOverflow,
    bool? markersAutoAligned,
    double? markersAnchor,
    double? markerSize,
    double? markerSizeScale,
    PositionedOffset? markersOffset,
    AlignmentGeometry? markersAlignment,
    Decoration? markerDecoration,
    EdgeInsets? markerMargin,
    EdgeInsets? cellMargin,
    EdgeInsets? cellPadding,
    AlignmentGeometry? cellAlignment,
    double? rangeHighlightScale,
    Color? rangeHighlightColor,
    bool? outsideDaysVisible,
    bool? isTodayHighlighted,
    TextStyle? todayTextStyle,
    Decoration? todayDecoration,
    TextStyle? selectedTextStyle,
    Decoration? selectedDecoration,
    TextStyle? rangeStartTextStyle,
    Decoration? rangeStartDecoration,
    TextStyle? rangeEndTextStyle,
    Decoration? rangeEndDecoration,
    TextStyle? withinRangeTextStyle,
    Decoration? withinRangeDecoration,
    TextStyle? outsideTextStyle,
    Decoration? outsideDecoration,
    TextStyle? disabledTextStyle,
    Decoration? disabledDecoration,
    TextStyle? holidayTextStyle,
    Decoration? holidayDecoration,
    TextStyle? weekendTextStyle,
    Decoration? weekendDecoration,
    TextStyle? weekNumberTextStyle,
    TextStyle? defaultTextStyle,
    Decoration? defaultDecoration,
    Decoration? rowDecoration,
    TableBorder? tableBorder,
    EdgeInsets? tablePadding,
    TextFormatter? dayTextFormatter,
  }) {
    return CalendarStyle(
      markersMaxCount: markersMaxCount ?? this.markersMaxCount,
      canMarkersOverflow: canMarkersOverflow ?? this.canMarkersOverflow,
      markersAutoAligned: markersAutoAligned ?? this.markersAutoAligned,
      markersAnchor: markersAnchor ?? this.markersAnchor,
      markerSize: markerSize ?? this.markerSize,
      markerSizeScale: markerSizeScale ?? this.markerSizeScale,
      markersOffset: markersOffset ?? this.markersOffset,
      markersAlignment: markersAlignment ?? this.markersAlignment,
      markerDecoration: markerDecoration ?? this.markerDecoration,
      markerMargin: markerMargin ?? this.markerMargin,
      cellMargin: cellMargin ?? this.cellMargin,
      cellPadding: cellPadding ?? this.cellPadding,
      cellAlignment: cellAlignment ?? this.cellAlignment,
      rangeHighlightScale: rangeHighlightScale ?? this.rangeHighlightScale,
      rangeHighlightColor: rangeHighlightColor ?? this.rangeHighlightColor,
      outsideDaysVisible: outsideDaysVisible ?? this.outsideDaysVisible,
      isTodayHighlighted: isTodayHighlighted ?? this.isTodayHighlighted,
      todayTextStyle: todayTextStyle ?? this.todayTextStyle,
      todayDecoration: todayDecoration ?? this.todayDecoration,
      selectedTextStyle: selectedTextStyle ?? this.selectedTextStyle,
      selectedDecoration: selectedDecoration ?? this.selectedDecoration,
      rangeStartTextStyle: rangeStartTextStyle ?? this.rangeStartTextStyle,
      rangeStartDecoration: rangeStartDecoration ?? this.rangeStartDecoration,
      rangeEndTextStyle: rangeEndTextStyle ?? this.rangeEndTextStyle,
      rangeEndDecoration: rangeEndDecoration ?? this.rangeEndDecoration,
      withinRangeTextStyle: withinRangeTextStyle ?? this.withinRangeTextStyle,
      withinRangeDecoration: withinRangeDecoration ?? this.withinRangeDecoration,
      outsideTextStyle: outsideTextStyle ?? this.outsideTextStyle,
      outsideDecoration: outsideDecoration ?? this.outsideDecoration,
      disabledTextStyle: disabledTextStyle ?? this.disabledTextStyle,
      disabledDecoration: disabledDecoration ?? this.disabledDecoration,
      holidayTextStyle: holidayTextStyle ?? this.holidayTextStyle,
      holidayDecoration: holidayDecoration ?? this.holidayDecoration,
      weekendTextStyle: weekendTextStyle ?? this.weekendTextStyle,
      weekendDecoration: weekendDecoration ?? this.weekendDecoration,
      weekNumberTextStyle: weekNumberTextStyle ?? this.weekNumberTextStyle,
      defaultTextStyle: defaultTextStyle ?? this.defaultTextStyle,
      defaultDecoration: defaultDecoration ?? this.defaultDecoration,
      rowDecoration: rowDecoration ?? this.rowDecoration,
      tableBorder: tableBorder ?? this.tableBorder,
      tablePadding: tablePadding ?? this.tablePadding,
      dayTextFormatter: dayTextFormatter ?? this.dayTextFormatter,
    );
  }
}
